/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/watchdog_timer.v:3.1-38.10" *)
module watchdog_timer(clk, rst, enable, kick, timeout, wdt_reset, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire [1:0] _03_;
  (* src = "rtl/watchdog_timer.v:29.14-29.30" *)
  wire _04_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/watchdog_timer.v:33.18-33.30|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _05_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/watchdog_timer.v:33.18-33.30|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _06_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/watchdog_timer.v:33.18-33.30|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _07_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [3:0] _08_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [3:0] _09_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _10_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [3:0] _11_;
  wire _12_;
  wire _13_;
  (* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _14_;
  (* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _15_;
  (* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _16_;
  (* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _17_;
  (* src = "rtl/watchdog_timer.v:6.37-6.40" *)
  input clk;
  wire clk;
  (* src = "rtl/watchdog_timer.v:13.37-13.42" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "rtl/watchdog_timer.v:8.37-8.43" *)
  input enable;
  wire enable;
  (* src = "rtl/watchdog_timer.v:9.37-9.41" *)
  input kick;
  wire kick;
  (* src = "rtl/watchdog_timer.v:7.37-7.40" *)
  input rst;
  wire rst;
  (* src = "rtl/watchdog_timer.v:10.37-10.44" *)
  input [3:0] timeout;
  wire [3:0] timeout;
  (* src = "rtl/watchdog_timer.v:12.37-12.46" *)
  output wdt_reset;
  reg wdt_reset;
  (* src = "rtl/watchdog_timer.v:16.1-36.4" *)
  always @(posedge clk)
    if (_00_) wdt_reset <= 1'h0;
    else wdt_reset <= _04_;
  (* src = "rtl/watchdog_timer.v:16.1-36.4" *)
  always @(posedge clk)
    if (_00_) count[0] <= 1'h0;
    else if (!_04_) count[0] <= _06_[0];
  (* src = "rtl/watchdog_timer.v:16.1-36.4" *)
  always @(posedge clk)
    if (_00_) count[1] <= 1'h0;
    else if (!_04_) count[1] <= _07_[1];
  (* src = "rtl/watchdog_timer.v:16.1-36.4" *)
  always @(posedge clk)
    if (_00_) count[2] <= 1'h0;
    else if (!_04_) count[2] <= _07_[2];
  (* src = "rtl/watchdog_timer.v:16.1-36.4" *)
  always @(posedge clk)
    if (_00_) count[3] <= 1'h0;
    else if (!_04_) count[3] <= _07_[3];
  assign _02_ = rst |(* src = {0{1'b0}} *)  kick;
  assign _00_ = _02_ |(* src = {0{1'b0}} *)  _01_;
  assign _03_[0] = _10_[0] &(* src = "rtl/watchdog_timer.v:29.14-29.30" *)  _10_[1];
  assign _13_ = _03_[0] &(* src = "rtl/watchdog_timer.v:29.14-29.30" *)  _03_[1];
  assign _04_ = _12_ |(* src = {0{1'b0}} *)  _13_;
  assign _01_ = ~(* src = {0{1'b0}} *) enable;
  assign _12_ = ~(* src = "rtl/watchdog_timer.v:29.14-29.30" *) _09_[3];
  assign _08_[2] = ~(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) count[2];
  assign _08_[3] = ~(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) count[3];
  assign _06_[0] = ~(* src = "rtl/watchdog_timer.v:33.18-33.30|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) count[0];
  assign _08_[1] = ~(* src = "rtl/watchdog_timer.v:33.18-33.30|/usr/local/bin/../share/yosys/techmap.v:279.31-279.37" *) count[1];
  assign _10_[0] = timeout[0] ^(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:288.13-288.20" *)  _06_[0];
  assign _10_[1] = timeout[1] ^(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:288.13-288.20" *)  _08_[1];
  assign _10_[2] = timeout[2] ^(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:288.13-288.20" *)  _08_[2];
  assign _10_[3] = timeout[3] ^(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:288.13-288.20" *)  _08_[3];
  assign _11_[0] = timeout[0] &(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.42-286.49" *)  _06_[0];
  assign _11_[1] = timeout[1] &(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.42-286.49" *)  _08_[1];
  assign _11_[2] = timeout[2] &(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.42-286.49" *)  _08_[2];
  assign _11_[3] = timeout[3] &(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.42-286.49" *)  _08_[3];
  assign _07_[1] = count[1] ^(* src = "rtl/watchdog_timer.v:33.18-33.30|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  count[0];
  assign _07_[2] = count[2] ^(* src = "rtl/watchdog_timer.v:33.18-33.30|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _05_[1];
  assign _07_[3] = count[3] ^(* src = "rtl/watchdog_timer.v:33.18-33.30|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _05_[2];
  assign _14_ = _10_[1] &(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _09_[0];
  assign _15_ = _10_[3] &(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _11_[2];
  assign _16_ = _03_[1] &(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _09_[1];
  assign _03_[1] = _10_[3] &(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _10_[2];
  assign _09_[0] = _11_[0] |(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:231.10-231.28" *)  _10_[0];
  assign _09_[1] = _11_[1] |(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _14_;
  assign _17_ = _11_[3] |(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _15_;
  assign _09_[3] = _17_ |(* src = "rtl/watchdog_timer.v:29.14-29.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _16_;
  assign _05_[1] = count[1] &(* src = "rtl/watchdog_timer.v:33.18-33.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  count[0];
  assign _05_[2] = count[2] &(* src = "rtl/watchdog_timer.v:33.18-33.30|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _05_[1];
  assign _05_[0] = count[0];
  assign _06_[3:1] = count[3:1];
  assign _07_[0] = _06_[0];
  assign _08_[0] = _06_[0];
endmodule
